/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MyOrdersRouteImport } from './pages/MyOrders'
import { Route as MyListingsRouteImport } from './pages/MyListings'
import { Route as MessagesRouteImport } from './pages/Messages'
import { Route as MarketplaceRouteImport } from './pages/Marketplace'
import { Route as ManageListingRouteImport } from './pages/ManageListing'
import { Route as ListingDetailsRouteImport } from './pages/ListingDetails'
import { Route as AutionRouteImport } from './pages/Aution'
import { Route as IndexRouteImport } from './pages/index'

const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/MyOrders',
  path: '/MyOrders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/MyListings',
  path: '/MyListings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/Messages',
  path: '/Messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/Marketplace',
  path: '/Marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageListingRoute = ManageListingRouteImport.update({
  id: '/ManageListing',
  path: '/ManageListing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingDetailsRoute = ListingDetailsRouteImport.update({
  id: '/ListingDetails',
  path: '/ListingDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const AutionRoute = AutionRouteImport.update({
  id: '/Aution',
  path: '/Aution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
  id:
    | '__root__'
    | '/'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutionRoute: typeof AutionRoute
  ListingDetailsRoute: typeof ListingDetailsRoute
  ManageListingRoute: typeof ManageListingRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  MyListingsRoute: typeof MyListingsRoute
  MyOrdersRoute: typeof MyOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/MyOrders': {
      id: '/MyOrders'
      path: '/MyOrders'
      fullPath: '/MyOrders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MyListings': {
      id: '/MyListings'
      path: '/MyListings'
      fullPath: '/MyListings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Messages': {
      id: '/Messages'
      path: '/Messages'
      fullPath: '/Messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Marketplace': {
      id: '/Marketplace'
      path: '/Marketplace'
      fullPath: '/Marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManageListing': {
      id: '/ManageListing'
      path: '/ManageListing'
      fullPath: '/ManageListing'
      preLoaderRoute: typeof ManageListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ListingDetails': {
      id: '/ListingDetails'
      path: '/ListingDetails'
      fullPath: '/ListingDetails'
      preLoaderRoute: typeof ListingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Aution': {
      id: '/Aution'
      path: '/Aution'
      fullPath: '/Aution'
      preLoaderRoute: typeof AutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutionRoute: AutionRoute,
  ListingDetailsRoute: ListingDetailsRoute,
  ManageListingRoute: ManageListingRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  MyListingsRoute: MyListingsRoute,
  MyOrdersRoute: MyOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
