/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MyOrdersRouteImport } from './pages/MyOrders'
import { Route as MyListingsRouteImport } from './pages/MyListings'
import { Route as MessagesRouteImport } from './pages/Messages'
import { Route as MarketplaceRouteImport } from './pages/Marketplace'
import { Route as ManageListingRouteImport } from './pages/ManageListing'
import { Route as ListingDetailsRouteImport } from './pages/ListingDetails'
import { Route as AutionRouteImport } from './pages/Aution'
import { Route as MemberRegisterPageRouteRouteImport } from './pages/MemberRegisterPage/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as MemberRegisterPageIndexRouteImport } from './pages/MemberRegisterPage/index'
import { Route as AuctionsIdRouteImport } from './pages/auctions.$id'
import { Route as MemberRegisterPageRegisterRouteImport } from './pages/MemberRegisterPage/register'
import { Route as MemberRegisterPageForgotPasswordRouteImport } from './pages/MemberRegisterPage/forgot-password'

const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/MyOrders',
  path: '/MyOrders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/MyListings',
  path: '/MyListings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/Messages',
  path: '/Messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/Marketplace',
  path: '/Marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageListingRoute = ManageListingRouteImport.update({
  id: '/ManageListing',
  path: '/ManageListing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingDetailsRoute = ListingDetailsRouteImport.update({
  id: '/ListingDetails',
  path: '/ListingDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const AutionRoute = AutionRouteImport.update({
  id: '/Aution',
  path: '/Aution',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRegisterPageRouteRoute = MemberRegisterPageRouteRouteImport.update({
  id: '/MemberRegisterPage',
  path: '/MemberRegisterPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRegisterPageIndexRoute = MemberRegisterPageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRegisterPageRouteRoute,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRegisterPageRegisterRoute =
  MemberRegisterPageRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => MemberRegisterPageRouteRoute,
  } as any)
const MemberRegisterPageForgotPasswordRoute =
  MemberRegisterPageForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => MemberRegisterPageRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/MemberRegisterPage': typeof MemberRegisterPageRouteRouteWithChildren
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
  '/MemberRegisterPage/forgot-password': typeof MemberRegisterPageForgotPasswordRoute
  '/MemberRegisterPage/register': typeof MemberRegisterPageRegisterRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/MemberRegisterPage/': typeof MemberRegisterPageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
  '/MemberRegisterPage/forgot-password': typeof MemberRegisterPageForgotPasswordRoute
  '/MemberRegisterPage/register': typeof MemberRegisterPageRegisterRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/MemberRegisterPage': typeof MemberRegisterPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/MemberRegisterPage': typeof MemberRegisterPageRouteRouteWithChildren
  '/Aution': typeof AutionRoute
  '/ListingDetails': typeof ListingDetailsRoute
  '/ManageListing': typeof ManageListingRoute
  '/Marketplace': typeof MarketplaceRoute
  '/Messages': typeof MessagesRoute
  '/MyListings': typeof MyListingsRoute
  '/MyOrders': typeof MyOrdersRoute
  '/MemberRegisterPage/forgot-password': typeof MemberRegisterPageForgotPasswordRoute
  '/MemberRegisterPage/register': typeof MemberRegisterPageRegisterRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/MemberRegisterPage/': typeof MemberRegisterPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/MemberRegisterPage'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
    | '/MemberRegisterPage/forgot-password'
    | '/MemberRegisterPage/register'
    | '/auctions/$id'
    | '/MemberRegisterPage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
    | '/MemberRegisterPage/forgot-password'
    | '/MemberRegisterPage/register'
    | '/auctions/$id'
    | '/MemberRegisterPage'
  id:
    | '__root__'
    | '/'
    | '/MemberRegisterPage'
    | '/Aution'
    | '/ListingDetails'
    | '/ManageListing'
    | '/Marketplace'
    | '/Messages'
    | '/MyListings'
    | '/MyOrders'
    | '/MemberRegisterPage/forgot-password'
    | '/MemberRegisterPage/register'
    | '/auctions/$id'
    | '/MemberRegisterPage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberRegisterPageRouteRoute: typeof MemberRegisterPageRouteRouteWithChildren
  AutionRoute: typeof AutionRoute
  ListingDetailsRoute: typeof ListingDetailsRoute
  ManageListingRoute: typeof ManageListingRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  MyListingsRoute: typeof MyListingsRoute
  MyOrdersRoute: typeof MyOrdersRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/MyOrders': {
      id: '/MyOrders'
      path: '/MyOrders'
      fullPath: '/MyOrders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MyListings': {
      id: '/MyListings'
      path: '/MyListings'
      fullPath: '/MyListings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Messages': {
      id: '/Messages'
      path: '/Messages'
      fullPath: '/Messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Marketplace': {
      id: '/Marketplace'
      path: '/Marketplace'
      fullPath: '/Marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManageListing': {
      id: '/ManageListing'
      path: '/ManageListing'
      fullPath: '/ManageListing'
      preLoaderRoute: typeof ManageListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ListingDetails': {
      id: '/ListingDetails'
      path: '/ListingDetails'
      fullPath: '/ListingDetails'
      preLoaderRoute: typeof ListingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Aution': {
      id: '/Aution'
      path: '/Aution'
      fullPath: '/Aution'
      preLoaderRoute: typeof AutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemberRegisterPage': {
      id: '/MemberRegisterPage'
      path: '/MemberRegisterPage'
      fullPath: '/MemberRegisterPage'
      preLoaderRoute: typeof MemberRegisterPageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemberRegisterPage/': {
      id: '/MemberRegisterPage/'
      path: '/'
      fullPath: '/MemberRegisterPage/'
      preLoaderRoute: typeof MemberRegisterPageIndexRouteImport
      parentRoute: typeof MemberRegisterPageRouteRoute
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MemberRegisterPage/register': {
      id: '/MemberRegisterPage/register'
      path: '/register'
      fullPath: '/MemberRegisterPage/register'
      preLoaderRoute: typeof MemberRegisterPageRegisterRouteImport
      parentRoute: typeof MemberRegisterPageRouteRoute
    }
    '/MemberRegisterPage/forgot-password': {
      id: '/MemberRegisterPage/forgot-password'
      path: '/forgot-password'
      fullPath: '/MemberRegisterPage/forgot-password'
      preLoaderRoute: typeof MemberRegisterPageForgotPasswordRouteImport
      parentRoute: typeof MemberRegisterPageRouteRoute
    }
  }
}

interface MemberRegisterPageRouteRouteChildren {
  MemberRegisterPageForgotPasswordRoute: typeof MemberRegisterPageForgotPasswordRoute
  MemberRegisterPageRegisterRoute: typeof MemberRegisterPageRegisterRoute
  MemberRegisterPageIndexRoute: typeof MemberRegisterPageIndexRoute
}

const MemberRegisterPageRouteRouteChildren: MemberRegisterPageRouteRouteChildren =
  {
    MemberRegisterPageForgotPasswordRoute:
      MemberRegisterPageForgotPasswordRoute,
    MemberRegisterPageRegisterRoute: MemberRegisterPageRegisterRoute,
    MemberRegisterPageIndexRoute: MemberRegisterPageIndexRoute,
  }

const MemberRegisterPageRouteRouteWithChildren =
  MemberRegisterPageRouteRoute._addFileChildren(
    MemberRegisterPageRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberRegisterPageRouteRoute: MemberRegisterPageRouteRouteWithChildren,
  AutionRoute: AutionRoute,
  ListingDetailsRoute: ListingDetailsRoute,
  ManageListingRoute: ManageListingRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  MyListingsRoute: MyListingsRoute,
  MyOrdersRoute: MyOrdersRoute,
  AuctionsIdRoute: AuctionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
